### ISSUE TITLE
Give Button

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#110]
Font weight for Vitesse should be 400, not 500. Also, please center vertically.

![image](https://cloud.githubusercontent.com/assets/26605197/24778802/cf425362-1ae9-11e7-9cb6-596c86707a49.png)

**Comment by Aleniras** [comment]
Is this responsive? So the button will increase/decrease in width pending their title? If so, please make sure there's a max width of the column size so we don't run into problems.

**Comment by kebowdog** [comment]
I've fixed the font weight and centering. They can set a max width using CSS. As for making it responsive, what kind of responsive features do you need? Does the text need to shrink for mobile devices or something like that?

**Comment by Aleniras** [comment]
Thanks kevin! For now, lets leave it be the same size on desktop or mobile. I just didn't want it to end up awkwardly like this was all: 

![image](https://cloud.githubusercontent.com/assets/26605197/24818487/017fa000-1b9e-11e7-8b59-1d6b757b3b35.png)

**Comment by kebowdog** [comment]
Cool. I'll close this issue as soon as the pull request goes through.
