### ISSUE TITLE
Area Footer Vitesse Weight

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#111]
Font weight for Vitesse headers everywhere should be 400, not 500

Please make to look like this:
![image](https://cloud.githubusercontent.com/assets/26605197/24778925/718ed348-1aea-11e7-8b00-bdc31f22b3aa.png)

Currently looks like this:
![image](https://cloud.githubusercontent.com/assets/26605197/24778945/97665c44-1aea-11e7-8243-83fa6c361025.png)

**Comment by kebowdog** [comment]
I just checked the demo pages and it's the correct font-weight now.
