### ISSUE TITLE
Margin if no search bar

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#112]
The margin on the right needs to always match the margin on the left. Please add padding between end of "sign out" and end of page. 

![image](https://cloud.githubusercontent.com/assets/26605197/24779013/e09dc6fe-1aea-11e7-8935-8b1d09d63e0a.png)

**Comment by kebowdog** [comment]
Found the problem - this is just because the demo page was using a div to fake the look of the header. I'll update it to use a real header.
