### ISSUE TITLE
Should be Sign In / Sign Out instead of Login / Sign Out

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#114]
We have Sign In some places, and Login some places. Please make everything Sign In/Sign Out

![image](https://cloud.githubusercontent.com/assets/26605197/24779431/9ce544ac-1aed-11e7-9084-7eb63c0f7d6b.png)

![image](https://cloud.githubusercontent.com/assets/26605197/24779114/6fe633a0-1aeb-11e7-920c-3c4f1a418823.png)

![image](https://cloud.githubusercontent.com/assets/26605197/24779122/82335204-1aeb-11e7-9b2c-183c322f299c.png)

**Comment by kebowdog** [comment]
It looks like the only spot in the demo pages still showing this is at the bottom of http://2017-components-demo.cdn.byu.edu/byu-user-info.html. I'll fix this in my next PR.
