### ISSUE TITLE
Search Page is lacking examples

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#115]
Can we get this page updated?  Currently no search images appearing
http://2017-components-demo.cdn.byu.edu/byu-search.html

![image](https://cloud.githubusercontent.com/assets/26605197/24779165/cb572802-1aeb-11e7-9ce6-2119eea78a0f.png)

**Comment by kebowdog** [comment]
Fixed in the last PR, examples are now appearing.
