### ISSUE TITLE
Centered links on navigation bar

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#118]
Links on nav bar should be centered, unless there are 3 or less. Then please left align with the beginning of the College/Department (see green line below)

![image](https://cloud.githubusercontent.com/assets/26605197/24779252/6ca7d56c-1aec-11e7-8b8f-e91e8e79a7ad.png)

![image](https://cloud.githubusercontent.com/assets/26605197/24779296/b3aac776-1aec-11e7-88f0-4cc25ab110f8.png)

**Comment by kebowdog** [comment]
This should be fixed by PR #127
