### ISSUE TITLE
byu-header-content on mobile shouldn't have padding

### ISSUE THREAD

**Issue by katrialesser** [byuweb/2017-components#137]
![image](https://cloud.githubusercontent.com/assets/12898896/24933449/97193490-1ed3-11e7-9bce-e34856335d17.png)

**Comment by katrialesser** [comment]
just need to specify padding 0 for mobile

**Comment by michaelpratt28** [comment]
This is already fixed with issue #62

**Comment by kebowdog** [comment]
Already fixed, just waiting for the CDN to update.
