### ISSUE TITLE
iPad view 

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#143]
Is this an accurate view of where the code is at for iPads?
Seems the search bar needs some love

![img_0077](https://cloud.githubusercontent.com/assets/26605197/24988845/d6d2e2a0-1fc5-11e7-9807-d5bc87479b06.PNG)

**Comment by michaelpratt28** [comment]
This issue is already noted in issue #91

**Comment by ThatJoeMoore** [comment]
Resolved in #91
