### ISSUE TITLE
Department Name font

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#39]
Mobile view should have a wrapped title with smaller font instead of ellipses (see instructions)

<img width="317" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210220/04d73978-0eee-11e7-9ca3-cadd627d913f.png">

<img width="400" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210241/1662894a-0eee-11e7-923c-51d5563bc662.png">

**Comment by Aleniras** [comment]
As page width shrinks, space between "BYU" and start of Department name should still remain the same as full width.

<img width="924" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210094/a7e6682e-0eed-11e7-9083-4335eb69d421.png">

**Comment by Aleniras** [comment]
Margins:
Amount of blue space before "BYU" on left is perfect. Please add padding on the right side of menu icon to match.

<img width="400" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210283/40acf2b2-0eee-11e7-82ac-4b3c946d8681.png">

**Comment by Aleniras** [comment]
Please make sure grey button in search box is larger than menu icon above it. Menu icon and search icon should be the same size. 

<img width="318" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210377/8146d522-0eee-11e7-8fd7-59cf5db4388f.png">

<img width="323" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210409/9b1b755c-0eee-11e7-9a1f-a1a9002c9a1d.png">

**Comment by Aleniras** [comment]
Please shrink line height between Brigham Young University and copyright line. 

<img width="462" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210450/c8e64868-0eee-11e7-8560-554a32f6ac67.png">

<img width="426" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210458/d3633d3c-0eee-11e7-930d-3d4b4fb40020.png">

**Comment by Aleniras** [comment]
Do we have the option of adding a subtitle?

<img width="320" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210742/a4be487c-0eef-11e7-9e45-2335e38b3561.png">

**Comment by Aleniras** [comment]
Logged in name should appear a different blue:

<img width="306" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210808/d9d0bc5c-0eef-11e7-8375-1b921bce22a6.png">

<img width="216" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210793/cb881a0a-0eef-11e7-8069-fe2f28c13392.png">

**Comment by Aleniras** [comment]
Is there anywhere for me to check the logged in view on the mobile menu?

<img width="321" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210915/304a3176-0ef0-11e7-9837-bc7640e1ad05.png">

**Comment by rburkey87** [comment]
Pull request has been created for Katria to review. Should be good to go!

**Comment by rburkey87** [comment]
pull request has been merged @Aleniras

**Comment by rburkey87** [comment]
actually, hold up - it looks like some padding has been added during one of the merges. I'll fix it.

**Comment by rburkey87** [comment]
padding fixed and merged.

**Comment by kebowdog** [comment]
just checked on master and it's looking great.
