### ISSUE TITLE
Search Box + proportions

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#43]
Please make sure grey button in search box is larger than menu icon above it. Menu icon and search icon should be the same size. 

<img width="318" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210377/8146d522-0eee-11e7-8fd7-59cf5db4388f.png">

<img width="323" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210409/9b1b755c-0eee-11e7-9a1f-a1a9002c9a1d.png">

**Comment by kebowdog** [comment]
Fixed by @michaelpratt28
