### ISSUE TITLE
Footer line height

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#44]
Try 7px line-height between Brigham Young University and copyright line. 
Also, lets increase the width of BYU logo to 450 px so it is wider than copyright line

<img width="462" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210450/c8e64868-0eee-11e7-8560-554a32f6ac67.png">

<img width="426" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210458/d3633d3c-0eee-11e7-930d-3d4b4fb40020.png">

**Comment by kebowdog** [comment]
Do you want it 450px in mobile as well? Or should it shrink to 380px (the min width we're supporting for mobile)?

**Comment by Aleniras** [comment]
that's fine to shrink on mobile.

**Comment by kebowdog** [comment]
As far as the line height between Brigham Young University and the copyright line, the spacing is in the BYU logo itself. I can remove some of the spacing by using a negative margin, then using a pixel ruler to measure distance. This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/19493582/24273521/6f4efc8c-0fe8-11e7-9735-c1c3ff09a400.png)

**Comment by kebowdog** [comment]
Fixed by PR #69
