### ISSUE TITLE
Subtitle Option?

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#45]
Do we have the option of adding a subtitle?

<img width="320" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210742/a4be487c-0eef-11e7-9e45-2335e38b3561.png">

<img width="734" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210758/b35a96d8-0eef-11e7-9823-407af7d65979.png">

**Comment by katrialesser** [comment]
Aleni, I believe this is in place, let me see if we have an example somewhere.

**Comment by kebowdog** [comment]
It looks like there isn't a subtitle or supertitle option. Should we add that as a new slot?

**Comment by kebowdog** [comment]
fixed in PR #103
