### ISSUE TITLE
Logged-in name formatting

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#46]
Logged in name should appear a different blue:

<img width="306" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210808/d9d0bc5c-0eef-11e7-8375-1b921bce22a6.png">

<img width="216" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210793/cb881a0a-0eef-11e7-8069-fe2f28c13392.png">

**Comment by katrialesser** [comment]
Okay, i see where this is - the color is specified on the Desktop Header

**Comment by rburkey87** [comment]
ready to go, but need to merge other PR before rebasing and reopening PR for username-fix

**Comment by kebowdog** [comment]
This is working in chrome, but nor Firefox, so I'll leave this issue open for now.

**Comment by kebowdog** [comment]
Forgot to close this, but it's been working for the last several commits.
