### ISSUE TITLE
Should be "Sign In" instead of "Log In"

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#48]
<img width="198" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24211464/c2e1063a-0ef1-11e7-8db6-33ef8fb30bf2.png">

**Comment by katrialesser** [comment]
This is specific to Kevin's version, i believe. he can update his. in all our examples i believe we have updated it to sign in.

**Comment by kebowdog** [comment]
Katria is correct. I've updated my CMS theme to reflect this, and confirmed that in the examples/documentation it's always sign in/out.
