### ISSUE TITLE
search

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#49]
I'm aware this isn't working quite yet, but once it is - can we just make sure that the functionality to hit enter to search works the same as clicking the icon to search?

Also this needs to be big enough that the "search" text can be the same size as text in the nav bar beneath it - - in gotham 500.

<img width="201" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24212158/f6b38698-0ef3-11e7-8bed-c75965a0c785.png">

**Comment by Aleniras** [comment]
Also this needs to be big enough that the "search" text can be the same size as text in the nav bar beneath it.

**Comment by michaelpratt28** [comment]
I created a branch called byu-search-fix. As far as the search functionality goes, there were a couple small errors in the markup that I resolved. I fixed an opening div tag to match it's closing form tag and added an onsubmit to call an existing function in the script.js called "formSubmitHandler". I think that's all it needed. I'll work on the text size.
