### ISSUE TITLE
Max Width

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#62]
Please set the max width of the header and footer at 1200px. This should be the default, with the option to be be full width if they choose.

**Comment by kebowdog** [comment]
We've got the max width working, we just need to add an option for full-width now.

**Comment by kebowdog** [comment]
Looks like we'll want to update the demo pages to match this as well.

**Comment by kebowdog** [comment]
The latest pull requests update it to allow full-width, and the demo pages have been updated to have full width.
