### ISSUE TITLE
Font weight

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#64]
Please change font weight to 500 instead of 400 on gotham everywhere **except** the copyright line in the picture below

<img width="498" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24272677/f3597cb4-0fe3-11e7-8160-b4eef5e06343.png">

**Comment by Gi60s** [comment]
FYI: I've updated the menu to use this new weight. It still awaits merge.

**Comment by rburkey87** [comment]
This should be fixed and merged now, yes?
