### ISSUE TITLE
First Name displayed

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#66]
Need to make the first name what is displayed, instead of netID

<img width="295" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24272738/422acfe6-0fe4-11e7-9d16-8ae3a129fbc8.png">

**Comment by katrialesser** [comment]
This is something to be documented and explained in the demo. Each site/template/theme will need to implement this; the themes can provide several default lines so they know which to enable depending on how their site login is set up.

**Comment by kebowdog** [comment]
I'll change the docs to reflect this, then close it.
