### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#70]
We'll need to adjust the social media icons in the footer.  (see pinned image on engineering board for instructions)

<img width="379" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24275880/6cfad770-0ff8-11e7-88e9-2b846111cc46.png">

**Comment by Aleniras** [comment]
This may be helpful:  https://brandcolors.net/

**Comment by michaelpratt28** [comment]
@Aleniras Just to clarify, are you wanting the social media icons to look like the attached photo above or are you wanting me to stick to the pinned image on the engineering board that looks like this:
![smicons](https://cloud.githubusercontent.com/assets/15473604/24878423/4d93f802-1df0-11e7-9c4a-0a7c5ae4dafd.PNG)
